FlightPlanner/FlightPlanner/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("main.urls")),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, serve, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, serve, document_root=settings.MEDIA_ROOT)

FlightPlanner/main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main'

urlpatterns = [
    url('^$', views.input_map, name='input_map'),
    url('^render_map/(?P<name>[\w\-]+)$', views.render_map, name='render_map'),
    # url('^test$', views.test, name='test'),
    url('^download_csv/(?P<name>[\w\-]+)$', views.download_csv, name='download_csv'),
]

FlightPlanner/main/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class KMLFile(models.Model):
    file_path = models.FileField(upload_to='files/', null=True)
    name = models.CharField(max_length=20)
    csv_file = models.FileField(upload_to='csv/', null=True)
    zone_no = models.IntegerField(default=0)
    zone_name = models.CharField(max_length=2, null=True)
    def __unicode__(self):
        return self.name

FlightPlanner/main/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from .models import *
from django.conf import settings
import os
from heightmap import *
from pyproj import Proj
from suncalc import solar_position
from datetime import datetime
from shadowmap import ShadowMap, get_projection_north_deviation
from math import sin, cos, tan, asin, atan2, pi
import ephem
import math
from django.core.files import File
import io
# from io import BytesIO
# 30 m srtm data from http://dwtkns.com/srtm30m/
numpy.set_printoptions(threshold=numpy.nan)

# Solar constants
rad = pi / 180.0
epochStart = datetime(1970, 1, 1)
J1970 = 2440588
J2000 = 2451545
dayMs = 24 * 60 * 60 * 1000
e = rad * 23.4397 # obliquity of the Earth

_MONTHNAMES = [None, "Jan", "Feb", "Mar", "Apr", "May", "Jun",
                    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

# Create your views here.
# For testing KML files
def render_map(request, name):
    return render(request, 'main/render_map.html', {"name":'kmlfile' + name+'.kml'})

def input_map(request):
    if request.method == 'POST':
        import utm
        data = request.POST
        # print data
        if (data['ne_lng'] == '' or data['ne_lat'] == '' or data['sw_lng'] == '' or data['sw_lat'] == ''):
            return redirect("main:input_map")
        ne_lng = float(data['ne_lng'])
        ne_lat = float(data['ne_lat'])
        sw_lng = float(data['sw_lng'])
        sw_lat = float(data['sw_lat'])
        try:
            x_resolution = int(data['x_res'])
            y_resolution = int(data['y_res'])
            GSD = float(data['gsd'])
            pixel_to_km = float(data['pixel_to_km'])    # hidden value
            if (x_resolution == 0 or y_resolution == 0 or GSD == 0 or pixel_to_km == 0):
                raise Exception
        except:
            return render(request, 'main/input_map.html')
        # print ne_lng, sw_lat, ne_lat, sw_lng
        NE_UTM_X, NE_UTM_Y, NE_UTM_ZONE_NO, NE_UTM_NAME = utm.from_latlon(ne_lat, ne_lng)
        SW_UTM_X, SW_UTM_Y, SW_UTM_ZONE_NO, SW_UTM_NAME = utm.from_latlon(sw_lat, sw_lng)
        # print NE_UTM_X, NE_UTM_Y, NE_UTM_ZONE_NO, NE_UTM_NAME
        # print SW_UTM_X, SW_UTM_Y, SW_UTM_ZONE_NO, SW_UTM_NAME
        if(NE_UTM_NAME!=SW_UTM_NAME or NE_UTM_ZONE_NO!=SW_UTM_ZONE_NO):
            return HttpResponse("UTM Zones do not match. Select a smaller region.")
        else:
            kml_file = generate_csv(x_resolution, y_resolution, SW_UTM_X, SW_UTM_Y, NE_UTM_X, NE_UTM_Y,  GSD, NE_UTM_ZONE_NO, NE_UTM_NAME, pixel_to_km)
            try:
                name = kml_file.name
            except:
                return kml_file
            # print kml_file.file_path.url
            kml_url = request.build_absolute_uri(kml_file.file_path.url)
            # print kml_file.name
            # return HttpResponse("UTM Zones do not match. Select a smaller region.")
            return render(request, 'main/final_map.html', {'kml_file':kml_file, 'kml_url':kml_url})
    else:
        return render(request, 'main/input_map.html')

def download_csv(request, name):
    kml_file = KMLFile.objects.get(name=name)
    response = HttpResponse(kml_file.csv_file, content_type="application/csv")
    response['Content-Disposition'] = 'attachment; filename=%s.csv' % name
    return response

def generate_csv(x_resolution, y_resolution, x1, y1, x2, y3,  GSD, zone_no, zone_name, pixel_to_km):
    import utm
    # print x_resolution, y_resolution, x1, y1, x2, y3,  GSD, zone_no, zone_name
    centres = mesh(x_resolution, y_resolution, x1, y1, x2, y3,  GSD, pixel_to_km)   # generates a matrix of coordinates for the path
    # print centres, 'centres'
    line_path = pathline(centres)   # converts the matrix into a 1d list, for the final path
    name_int=0
    centre_lat, centre_lon = utm.to_latlon((x1+x2)/2, (y1+y3)/2, zone_no, zone_name)
    while(1):
        try:
            temp_file = KMLFile.objects.get(name=str(name_int)) # Files are named using plain integers
            name_int += 1
            # print name_int
            continue
        except:
            break
    path = os.path.join(settings.MEDIA_ROOT, 'csv', 'csv' + str(name_int) + '.csv')
    # print path
    proj = Proj(proj='utm', zone=zone_no, ellps='WGS84')    # Proj instance for utm to lat long conversions
    elevation_dir = os.path.join(settings.MEDIA_ROOT, 'hgt')
    heightmap = SrtmHeightMap(centre_lat, centre_lon, 
                    x_resolution, y_resolution, proj, pixel_to_km, GSD, x1, y1, x2, y3,elevation_dir)
    csvfile = open(str(path), "w+b")
    filewriter = csv.writer(csvfile, delimiter=',', quoting=csv.QUOTE_MINIMAL)
    filewriter.writerow(['X', 'Y', 'Elevation'])
    tiles = {}
    for i in range(0, len(line_path)):
        lat, lng = utm.to_latlon((line_path[i]['X']), (line_path[i]['Y']), zone_no, zone_name)
        tile_key = SrtmHeightMap._tileKey(lat, lng)
        if not tiles.has_key(tile_key):
            try:
                tiles[tile_key] = SrtmHeightMap._loadTile(heightmap.data_dir, lat, lng)
            except:
                return HttpResponse("HGT data does not exist. Please copy %s file in the media/hgt folder."%(SrtmHeightMap._tileKey(lat, lng)))
            # print 'Loaded tile', tile_key
        v = tiles[tile_key].getAltitudeFromLatLon(lat, lng)
        # print line_path[i]['X'], line_path[i]['Y']
        filewriter.writerow([str(line_path[i]['X']), str(line_path[i]['Y']), v])   # , str(get_elevation(utm.to_latlon((line_path[i]['X']), (line_path[i]['Y']), zone_no, zone_name)))
    csvfile.close()
    # t = datetime.now()
    # print t
    dev = get_projection_north_deviation(heightmap.proj, heightmap.lat,heightmap.lng)
    # observer at the centre of the point of interest
    gatech = ephem.Observer()
    gatech.lon, gatech.lat = '%.2f'%heightmap.lng, '%.2f'%heightmap.lat # pyephem takes input as strings and not float!!!
    sun = ephem.Sun()
    # print gatech.date, heightmap.lng, heightmap.lat   # date by default is UTC which should be used as other calculations are made accordingly
    # print gatech.lon, gatech.lat
    sun.compute(gatech)
    # print("%s %s" % (sun.alt, sun.az))
    azimuth = sun.az
    altitude = sun.alt
    sunpos = {
        'azimuth' : degree_to_rad(azimuth),
        'altitude' : degree_to_rad(altitude)
    }
    sun_x = -sin(sunpos['azimuth'] - dev) * cos(sunpos['altitude'])
    sun_y = -cos(sunpos['azimuth'] - dev) * cos(sunpos['altitude'])
    sun_z = sin(sunpos['altitude'])
    shadowmap = ShadowMap(centre_lat, centre_lon, x_resolution, y_resolution, heightmap.size_x, heightmap.size_y, heightmap.proj, pixel_to_km, GSD, x1, y1, x2, y3, sun_x, sun_y, sun_z, heightmap, 1.5)
    render_matrix = shadowmap.render()
    # 0 means shadow, 1 means lit
    print render_matrix
    # print shadowmap.size_y, shadowmap.size_x
    #print render_matrix
    s = ephem.Sun()
    s.compute()
    o = ephem.Observer()
    o.lat = '%0.2f'%heightmap.lat
    o.lon = '%0.2f'%heightmap.lng
    # print o.lat, o.lon
    # print 'O', o.date
    # print render_matrix
    render_matrix=rever(render_matrix, shadowmap) # Single lined path for render_matrix
    # print o.next_rising(s), o.previous_setting(s)
    next_rising = ephem_to_datetime(o.next_rising(s))
    previous_setting = ephem_to_datetime(o.previous_setting(s))
    current_time = ephem_to_datetime(o.date)
    # print previous_setting, current_time, next_rising
    # Check if the path isn't plotted after sunset or before sunrise
    if next_rising.day == previous_setting.day: # Sun is set
        for i in xrange(0, len(render_matrix)):
            render_matrix[i] = 0
    kml_file = KMLFile()
    kml_file.name = str(name_int)
    # f = open(path)
    # kml_file.csv_file.save(str(kml_file.name)+'.csv', File(f))
    # kml_file.file_path.name = kml_path
    kml_file.save()
    kml_file.zone_name = zone_name
    kml_file.zone_no = zone_no
    kml_file.save()
    # print len(centres) == len(render_matrix)
    generate_kml(path, kml_file, render_matrix)
    i = 0
    new_path = os.path.join(settings.MEDIA_ROOT, 'csv', 'csv_final' + str(name_int) + '.csv')
    with open(path, 'rb') as inp, open(str(new_path), 'wb') as out:
        writer = csv.writer(out)
        count = 0
        for row in csv.reader(inp):
            if render_matrix[i] != 0:
                writer.writerow(row)
                count += 1
        if count == 0:
            writer.writerow(['X', 'Y', 'Elevation'])
        i += 1
    f = open(new_path)
    kml_file.csv_file.save(str(kml_file.name)+'.csv', File(f))
    os.remove(path)
    # print heightmap.heights
    # print render_matrix
    # print len(render_matrix) == shadowmap.size_x * shadowmap.size_y
    return kml_file

def degree_to_rad(degrees):
    degree_str = str(degrees).split(':')
    return math.radians(float(degree_str[0]) + float(degree_str[1])/60 + float(degree_str[2])/3600)

def ephem_to_datetime(ephem_date):
    ephem_date_list = str(ephem_date).split('/')
    ephem_date_list[1] = _MONTHNAMES[int(ephem_date_list[1])]
    ephem_date = '/'.join(ephem_date_list)
    return datetime.strptime(str(ephem_date), "%Y/%b/%d %H:%M:%S")
####################################    Main Functions    ####################################

import csv
import simplekml
import numpy as np

def generate_kml(filename, kml_file, render_matrix):
    import utm
    # print filename
    inputfile = csv.reader(open(filename,'r'))
    kml=simplekml.Kml()
    ls = kml.newlinestring(name="Journey path")
    fol = kml.newfolder(name="Points")
    zone_no = kml_file.zone_no
    zone_name = kml_file.zone_name
    header = inputfile.next()
    i = 1
    prev_val = None
    for row in inputfile:
        # print row[0], row[1]
        lat, lng = utm.to_latlon(float(row[0]), float(row[1]), zone_no, zone_name)
        try:
            ls.coords.addcoordinates([(lng, lat, float(row[2]) + 100.00)])  #longitude, latitude
            prev_val = float(row[2])

FlightPlanner/main/templates/main/final_map.html
<!DOCTYPE HTML>
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
	<link rel="stylesheet" href="https://openlayers.org/en/v4.6.5/css/ol.css" type="text/css">
    <style>
      .map {
        height: 100%;
        width: 100%;
      }
    </style>
    <script src="https://openlayers.org/en/v4.6.5/build/ol.js" type="text/javascript"></script>
      <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="index, all" />
    <title>UAV Flight Path</title>
    <link rel="stylesheet" href="{% static 'main/css/ol.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/ol3-layerswitcher.css' %}" type="text/css">
  </head>
  <body>
    <div id="info">&nbsp;</div>
    <div id="map" class="map"></div>
    <input type="button" value="3D / 2D" onclick="javascript:ol3d.setEnabled(!ol3d.getEnabled())" />
    <script src="{% static 'main/js/inject_ol3_cesium.js' %}"></script>
    <script src="{% static 'main/js/ol3-layerswitcher.js' %}"></script>
    <a href="{% url 'main:input_map' %}">Map Again?</a><br>
    <a href="{% url 'main:download_csv' kml_file.name %}">Download Corresponding CSV File</a>

    <script>
      var projection = ol.proj.get('EPSG:3857');


var ol2d = new ol.Map({
        target: 'map',
        layers: [
            new ol.layer.Tile({
                source: new ol.source.BingMaps({
                  imagerySet: 'Aerial',
                  key: 'AlNk4U61H2Tk9kCiRmzUws1dazVxUh6BUeV5YRJAq5_KEw-dsiKj7AbgYtFnS7mR'
                })
              }),
            new ol.layer.Vector({
                source: new ol.source.Vector({
                url: "{{kml_url}}",
                format: new ol.format.KML()
                })
            }),
            ],

        view: new ol.View({
            center: ol.proj.transform([78.044007, 30.341105], 'EPSG:4326', 'EPSG:3857'),
          projection: projection,
          zoom: 16
        })
});

//var displayFeatureInfo = function(pixel) {
//        var features = [];
//        ol2d.forEachFeatureAtPixel(pixel, function(feature) {
//          features.push(feature);
//        });
//        if (features.length > 0) {
//          var info = [];
//          var i, ii;
//          for (i = 0, ii = features.length; i < ii; ++i) {
//            info.push(features[i].get('name'));
//          }
//          document.getElementById('info').innerHTML = info.join(', ') || '(unknown)';
//          ol2d.getTarget().style.cursor = 'pointer';
//        } else {
//          document.getElementById('info').innerHTML = '&nbsp;';
//          ol2d.getTarget().style.cursor = '';
//        }
//      };
//
//      ol2d.on('pointermove', function(evt) {
//        if (evt.dragging) {
//          return;
//        }
//        var pixel = ol2d.getEventPixel(evt.originalEvent);
//        displayFeatureInfo(pixel);
//      });
//
//      ol2d.on('click', function(evt) {
//        displayFeatureInfo(evt.pixel);
//      });

// Layer Switcher functionality courtesy:
// https://github.com/walkermatt/ol3-layerswitcher
var layerSwitcher = new ol.control.LayerSwitcher({
        tipLabel: 'Legend' // Optional label for button
});
ol2d.addControl(layerSwitcher);

// 3D system ..
var ol3d = new olcs.OLCesium({map: ol2d});
var scene = ol3d.getCesiumScene();
var terrainProvider = new Cesium.CesiumTerrainProvider({
    url : 'https://assets.agi.com/stk-terrain/world'
});
scene.terrainProvider = terrainProvider;
    </script>
  </body>
</html>

FlightPlanner/main/templates/main/render_map.html
<!DOCTYPE html>
<html>
  <head>
    <title>KML</title>
    <link rel="stylesheet" href="https://openlayers.org/en/v4.6.5/css/ol.css" type="text/css">
    <!-- The line below is only needed for old environments like Internet Explorer and Android 4.x -->
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
    <script src="https://openlayers.org/en/v4.6.5/build/ol.js"></script>
  </head>
  <body>
    <div id="map" class="map"></div>
    <div id="info">&nbsp;</div>
    <script>
      var projection = ol.proj.get('EPSG:3857');

      <!--var raster = new ol.layer.Tile({-->
        <!--source: new ol.source.BingMaps({-->
          <!--imagerySet: 'Aerial',-->
          <!--key: 'AlNk4U61H2Tk9kCiRmzUws1dazVxUh6BUeV5YRJAq5_KEw-dsiKj7AbgYtFnS7mR'-->
        <!--})-->
      <!--});-->
      var raster = new ol.layer.Tile({
            source: new ol.source.OSM()
          });

      var vector = new ol.layer.Vector({
        source: new ol.source.Vector({
          url: "http://127.0.0.1:8000/media/files/{{name}}",
          format: new ol.format.KML()
        })
      });

      var map = new ol.Map({
        layers: [raster, vector],
        target: document.getElementById('map'),
        view: new ol.View({
          center: [876970.8463461736, 5859807.853963373],
          projection: projection,
          zoom: 10
        })
      });

      var displayFeatureInfo = function(pixel) {
        var features = [];
        map.forEachFeatureAtPixel(pixel, function(feature) {
          features.push(feature);
        });
        if (features.length > 0) {
          var info = [];
          var i, ii;
          for (i = 0, ii = features.length; i < ii; ++i) {
            info.push(features[i].get('name'));
          }
          document.getElementById('info').innerHTML = info.join(', ') || '(unknown)';
          map.getTarget().style.cursor = 'pointer';
        } else {
          document.getElementById('info').innerHTML = '&nbsp;';
          map.getTarget().style.cursor = '';
        }
      };

      map.on('pointermove', function(evt) {
        if (evt.dragging) {
          return;
        }
        var pixel = map.getEventPixel(evt.originalEvent);
        displayFeatureInfo(pixel);
      });

      map.on('click', function(evt) {
        displayFeatureInfo(evt.pixel);
      });
    </script>
  </body>
</html>

FlightPlanner/main/templates/main/test.html
<!DOCTYPE HTML>
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
	<link rel="stylesheet" href="https://openlayers.org/en/v4.6.5/css/ol.css" type="text/css">
    <style>
      .map {
        height: 100%;
        width: 100%;
      }
    </style>
    <script src="https://openlayers.org/en/v4.6.5/build/ol.js" type="text/javascript"></script>
      <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="index, all" />
    <title>UAV Flight Path</title>
    <link rel="stylesheet" href="{% static 'main/css/ol.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/ol3-layerswitcher.css' %}" type="text/css">
  </head>
  <body>
    <div id="info">&nbsp;</div>
    <div id="map" class="map"></div>
    <input type="button" value="3D / 2D" onclick="javascript:ol3d.setEnabled(!ol3d.getEnabled())" />
    <script src="{% static 'main/js/inject_ol3_cesium.js' %}"></script>
    <script src="{% static 'main/js/ol3-layerswitcher.js' %}"></script>
    <a href="{% url 'main:input_map' %}">Map Again?</a><br>
    <a href="{% url 'main:download_csv' kml_file.name %}">Download Corresponding CSV File</a>

    <script>
      var projection = ol.proj.get('EPSG:3857');


var ol2d = new ol.Map({
        target: 'map',
        layers: [
            new ol.layer.Tile({
                source: new ol.source.BingMaps({
                  imagerySet: 'Aerial',
                  key: 'AlNk4U61H2Tk9kCiRmzUws1dazVxUh6BUeV5YRJAq5_KEw-dsiKj7AbgYtFnS7mR'
                })
              }),
            new ol.layer.Vector({
                source: new ol.source.Vector({
                url: "{{kml_url}}",
                format: new ol.format.KML()
                })
            }),
            ],

        view: new ol.View({
            center: ol.proj.transform([78.044007, 30.341105], 'EPSG:4326', 'EPSG:3857'),
          projection: projection,
          zoom: 16
        })
});

//var displayFeatureInfo = function(pixel) {
//        var features = [];
//        ol2d.forEachFeatureAtPixel(pixel, function(feature) {
//          features.push(feature);
//        });
//        if (features.length > 0) {
//          var info = [];
//          var i, ii;
//          for (i = 0, ii = features.length; i < ii; ++i) {
//            info.push(features[i].get('name'));
//          }
//          document.getElementById('info').innerHTML = info.join(', ') || '(unknown)';
//          ol2d.getTarget().style.cursor = 'pointer';
//        } else {
//          document.getElementById('info').innerHTML = '&nbsp;';
//          ol2d.getTarget().style.cursor = '';
//        }
//      };
//
//      ol2d.on('pointermove', function(evt) {
//        if (evt.dragging) {
//          return;
//        }
//        var pixel = ol2d.getEventPixel(evt.originalEvent);
//        displayFeatureInfo(pixel);
//      });
//
//      ol2d.on('click', function(evt) {
//        displayFeatureInfo(evt.pixel);
//      });

// Layer Switcher functionality courtesy:
// https://github.com/walkermatt/ol3-layerswitcher
var layerSwitcher = new ol.control.LayerSwitcher({
        tipLabel: 'Legend' // Optional label for button
});
ol2d.addControl(layerSwitcher);

// 3D system ..
var ol3d = new olcs.OLCesium({map: ol2d});
var scene = ol3d.getCesiumScene();
var terrainProvider = new Cesium.CesiumTerrainProvider({
    url : 'https://assets.agi.com/stk-terrain/world'
});
scene.terrainProvider = terrainProvider;
    </script>
  </body>
</html>

FlightPlanner/main/templates/main/upload_file.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{% static 'main/css/materialize.min.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
<body>
    <div class="container">
        <div class="row">
            <form class="col s12">
              <div class="row">
                <div class="input-field col s6">
                  <input id="x1" type="text" class="validate">
                  <label for="x1">Lat 1</label>
                </div>
                <div class="input-field col s6">
                  <input id="y1" type="text" class="validate">
                  <label for="y1">Lon 1</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s6">
                  <input id="x2" type="text" class="validate">
                  <label for="x2">Lat 2</label>
                </div>
                <div class="input-field col s6">
                  <input id="y2" type="text" class="validate">
                  <label for="y2">Lon 2</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s6">
                  <input id="x3" type="text" class="validate">
                  <label for="x3">Lat 3</label>
                </div>
                <div class="input-field col s6">
                  <input id="y3" type="text" class="validate">
                  <label for="y3">Lon 3</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s6">
                  <input id="x4" type="text" class="validate">
                  <label for="x4">Lat 4</label>
                </div>
                <div class="input-field col s6">
                  <input id="y4" type="text" class="validate">
                  <label for="y4">Lon 4</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s6">
                  <input id="gsd" type="text" class="validate">
                  <label for="gsd">GSD</label>
                </div>
                <div class="input-field col s6">
                  <input id="pixel_to_km" type="text" class="validate" value="0.00001">
                  <label for="pixel_to_km">Pixel to KM</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s6">
                  <input id="x_res" type="text" class="validate">
                  <label for="x_res">X-Resolution</label>
                </div>
                <div class="input-field col s6">
                  <input id="y_res" type="text" class="validate">
                  <label for="y_res">Y-Resolution</label>
                </div>
              </div>
              <button type="submit" class="btn btn-primary btn-lg m-l-15 waves-effect">Submit</button>
            </form>
        </div>
        <hr>
        <br><br>
        <div class="row">
            <form action="{% url 'main:upload_file' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="k_file">
                <br><br>
                <button type="submit" class="btn btn-primary btn-lg m-l-15 waves-effect">Upload KML file</button>
            </form>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'main/js/materialize.min.js' %}"></script>
</body>
</html>